Repository WordPress/php-ai-client, pull requests merged in 2025-08, with the labels that each got.

#40 Run PHPCS on unit tests as well
  phpcs.xml.dist
  tests/traits/ArrayTransformationTestTrait.php
  tests/unit/Common/AbstractDataValueObjectTest.php
  tests/unit/Common/AbstractEnumTest.php
  tests/unit/Files/DTO/FileTest.php
  tests/unit/Files/Enums/FileTypeEnumTest.php
  tests/unit/Files/ValueObjects/MimeTypeTest.php
  tests/unit/Messages/DTO/MessagePartTest.php
  tests/unit/Messages/DTO/MessageTest.php
  tests/unit/Messages/DTO/ModelMessageTest.php
  tests/unit/Messages/DTO/SystemMessageTest.php
  tests/unit/Messages/DTO/UserMessageTest.php
  tests/unit/Operations/DTO/GenerativeAiOperationTest.php
  tests/unit/Providers/DTO/ProviderMetadataTest.php
  tests/unit/Providers/DTO/ProviderModelsMetadataTest.php
  tests/unit/Providers/Models/DTO/ModelConfigTest.php
  tests/unit/Providers/Models/DTO/ModelMetadataTest.php
  tests/unit/Providers/Models/DTO/ModelRequirementsTest.php
  tests/unit/Providers/Models/DTO/RequiredOptionTest.php
  tests/unit/Providers/Models/DTO/SupportedOptionTest.php
  tests/unit/Results/DTO/CandidateTest.php
  tests/unit/Results/DTO/GenerativeAiResultTest.php
  tests/unit/Results/DTO/TokenUsageTest.php
  tests/unit/Tools/DTO/FunctionCallTest.php
  tests/unit/Tools/DTO/FunctionDeclarationTest.php
  tests/unit/Tools/DTO/FunctionResponseTest.php
  tests/unit/Tools/DTO/ToolTest.php
  tests/unit/Tools/DTO/WebSearchTest.php
Labels: [Type] Enhancement

#42 Remove candidate token count
  src/Results/DTO/Candidate.php
  tests/unit/Common/AbstractDataTransferObjectTest.php
  tests/unit/Operations/DTO/GenerativeAiOperationTest.php
  tests/unit/Results/DTO/CandidateTest.php
  tests/unit/Results/DTO/GenerativeAiResultTest.php
Labels: [Type] Enhancement

#43 Fix typos
  CONTRIBUTING.md
  docs/ARCHITECTURE.md
  docs/REQUIREMENTS.md
Labels: [Type] Developer Documentation

#46 Update `ARCHITECTURE.md` with latest revisions and high-level proposed HTTP approach
  docs/ARCHITECTURE.md
  src/Providers/Contracts/ProviderOperationsHandlerInterface.php
  src/Tools/DTO/FunctionCall.php
  src/Tools/DTO/FunctionResponse.php
Labels: [Type] Developer Documentation

#51 Remove unnecessary tool abstraction in favor of passing function declarations and web search directly
  src/Providers/Models/DTO/ModelConfig.php
  src/Tools/DTO/Tool.php
  tests/unit/Providers/Models/DTO/ModelConfigTest.php
  tests/unit/Tools/DTO/ToolTest.php
Labels: [Type] Enhancement

#58 Fixes Function Call and Declaration DTOs
  src/Tools/DTO/FunctionCall.php
  src/Tools/DTO/FunctionDeclaration.php
  tests/unit/Tools/DTO/FunctionCallTest.php
  tests/unit/Tools/DTO/FunctionDeclarationTest.php
Labels: [Type] Bug

#49 Add the Prompt Builder
  src/Builders/PromptBuilder.php
  src/Common/AbstractDataTransferObject.php
  src/Common/AbstractEnum.php
  src/Common/Contracts/WithArrayTransformationInterface.php
  src/Files/DTO/File.php
  src/Messages/DTO/Message.php
  src/Messages/DTO/ModelMessage.php
  src/Messages/DTO/UserMessage.php
  src/Providers/Models/DTO/ModelConfig.php
  src/Providers/Models/DTO/ModelMetadata.php
  src/Providers/Models/DTO/RequiredOption.php
  src/Providers/Models/DTO/SupportedOption.php
  src/Providers/Models/Enums/OptionEnum.php
  src/Results/DTO/GenerativeAiResult.php
  tests/traits/ArrayTransformationTestTrait.php
  tests/unit/Builders/PromptBuilderTest.php
  tests/unit/Files/DTO/FileTest.php
  tests/unit/Messages/DTO/MessageTest.php
  tests/unit/Messages/DTO/ModelMessageTest.php
  tests/unit/Messages/DTO/UserMessageTest.php
  tests/unit/Providers/DTO/ProviderModelsMetadataTest.php
  tests/unit/Providers/Models/DTO/ModelMetadataTest.php
  tests/unit/Providers/Models/DTO/ModelRequirementsTest.php
  tests/unit/Providers/Models/DTO/RequiredOptionTest.php
  tests/unit/Providers/Models/DTO/SupportedOptionTest.php
  tests/unit/Providers/Models/Enums/OptionEnumTest.php
Labels: [Feature]

#55 Add the AiClient with testing suite
  src/AiClient.php
  src/Builders/PromptBuilder.php
  tests/traits/MockModelCreationTrait.php
  tests/unit/AiClientTest.php
Labels: [Feature]

#61 Implement image generation support
  cli.php
  src/Common/AbstractEnum.php
  src/Files/ValueObjects/MimeType.php
  src/ProviderImplementations/Google/GoogleImageGenerationModel.php
  src/ProviderImplementations/Google/GoogleModelMetadataDirectory.php
  src/ProviderImplementations/Google/GoogleProvider.php
  src/ProviderImplementations/OpenAi/OpenAiImageGenerationModel.php
  src/ProviderImplementations/OpenAi/OpenAiModelMetadataDirectory.php
  src/ProviderImplementations/OpenAi/OpenAiProvider.php
  src/Providers/Models/Enums/OptionEnum.php
  src/Providers/OpenAiCompatibleImplementation/AbstractOpenAiCompatibleImageGenerationModel.php
  src/polyfills.php
  tests/mocks/MockOpenAiCompatibleImageGenerationModel.php
  tests/unit/Providers/OpenAiCompatibleImplementation/AbstractOpenAiCompatibleImageGenerationModelTest.php
Labels: [Feature]

#73 Stores required options as enums not strings
  src/Providers/Models/DTO/ModelConfig.php
  tests/unit/Providers/Models/DTO/ModelConfigTest.php
Labels: [Type] Bug

#74 Adds PHP 7.4 compatibility checking and fix violations
  composer.json
  composer.lock
  phpcs.xml.dist
  src/Providers/Http/DTO/Request.php
  src/polyfills.php
Labels: [Type] Bug
